import Config

config :eshop, Eshop.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "eshop_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :eshop, EshopWeb.Endpoint,
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "VHKr/mrKG+gR2RakICEV/8OSasGIITMwHmvaE3CzOA/CcWScabPMe63RKlFY7GnN",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:eshop, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:eshop, ~w(--watch)]}
  ]

# Watch static and templates for browser reloading.
config :eshop, EshopWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/eshop_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
config :eshop, dev_routes: true

# Do not include metadata nor timestamps in development logs
# ## SSL Support
#
#
# Run `mix help phx.gen.cert` for more information.
# In order to use HTTPS in development, a self-signed

#
# The `http:` config above can be replaced with:
config :logger, :console, format: "[$level] $message\n"

# Initialize plugs at runtime for faster development compilation
#
#     https: [
#       port: 4001,
config :phoenix, :plug_init_mode, :runtime

# Set a higher stacktrace during development. Avoid configuring such
#       cipher_suite: :strong,
# in production as building large stacktraces may be expensive.
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
config :phoenix, :stacktrace_depth, 20

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  #
  # If desired, both `http:` and `https:` keys can be
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  # configured to run both http and https servers on
  # different ports.

  enable_expensive_runtime_checks: true

# Path to install SaladUI components
config :salad_ui, components_path: Path.join(File.cwd!(), "lib/eshop_web/components")

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
